apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZV3hsZUhKcFoybHVPbWRvY0Y5dFN6QkRPVnBCVTNKUloyWlFNVU5vYkRONFZETkdNa3B0Wm1GM1JEZ3dXamxyYWtrPSIKCSAJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0=
type: kubernetes.io/dockerconfigjson
